### ISSUE TITLE
Add support for policies which test against the `Host` header

### ISSUE THREAD

**Issue by mmassenzio** [CopilotIQ/opa-tests#5]
We currently do not support testing against the `Host` header (or any header, for that matter)
This should be added to the YAML structure of the `Test` (inside the `TestCase`) by, probably just adding a `Headers` `map`:
```
testcase:
  ...
  target:
    policy: allow
    package: copilotiq

  tests:
    - name: "create_user"
      expect: false
      token:
        sub: "alice@gmail.com"
        roles:
          - USER

      headers:
        Host: myserver.com
        User-Agent: "random agent 1.0.1"
      resource:
        path: "/users"
        method: POST
```
Headers are currently supported in `jwt-opa` (see [PR #45](https://github.com/massenz/jwt-opa/pull/45)) so this should be supported by tests too.
